{{- if and .Values.blackboxExporter.enabled .Values.blackboxExporter.metrics.enabled }}
{{- range .Values.blackboxExporter.metrics.serviceMonitor.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.names.fullname" $ }}-{{ .name }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.blackboxExporter.metrics.serviceMonitor.labels }}
    {{- include "common.tplvalues.render" (dict "value" $.Values.blackboxExporter.metrics.serviceMonitor.labels "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if $.Values.blackboxExporter.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ $.Values.blackboxExporter.metrics.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.standard" $ | nindent 6 }}
      {{- if $.Values.blackboxExporter.metrics.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.blackboxExporter.metrics.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
  endpoints:
    - port: {{ $.Values.blackboxExporter.metrics.serviceMonitor.endpoints.port }}
      scheme: {{ $.Values.blackboxExporter.metrics.serviceMonitor.endpoints.scheme }}
      path: {{ $.Values.blackboxExporter.metrics.serviceMonitor.endpoints.path }}
      {{- if $.Values.blackboxExporter.metrics.serviceMonitor.interval }}
      interval: {{ $.Values.blackboxExporter.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if $.Values.blackboxExporter.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.blackboxExporter.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      honorLabels: {{ $.Values.blackboxExporter.metrics.serviceMonitor.honorLabels }}
      {{- if $.Values.blackboxExporter.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" $.Values.blackboxExporter.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if $.Values.blackboxExporter.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" $.Values.blackboxExporter.metrics.serviceMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
      params:
        module:
          - {{ .module }}
        target:
          - {{ .url }}
      metricRelabelings:
        - sourceLabels: [instance]
          targetLabel: instance
          replacement: {{ .url }}
        - sourceLabels: [target]
          targetLabel: target
          replacement: {{ .name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
{{- end }}
{{- end }}
