apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: ues
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: ues
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: ues
    spec:
      {{- include "ueransim.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: ues
          image: {{ template "ueransim.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: GNB_HOSTNAME
              value: {{ .Values.gnb.hostname }}
          {{- if .Values.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- else }}
          args:
            - ue
            - -n
            - {{ .Values.count | quote }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/ueransim/ue.yaml
              subPath: "ue.yaml"
        {{- if .Values.blackboxExporter.enabled }}
        - name: blackbox-exporter
          image: {{ .Values.blackboxExporter.image }}
          {{- if .Values.blackboxExporter.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.blackboxExporter.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.blackboxExporter.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.blackboxExporter.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.blackboxExporter.ports }}
          ports: {{- include "common.tplvalues.render" (dict "value" .Values.blackboxExporter.ports "context" $) | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.blackboxExporter.resources | nindent 12 }}
          {{- with .Values.blackboxExporter.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.blackboxExporter.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.blackboxExporter.config.enabled }}
          volumeMounts:
            - name: bb-config
              mountPath: /config/blackbox.yaml
              subPath: blackbox.yaml
          {{- end }}
        {{- end }}
        {{- if .Values.routeUpdater.enabled }}
        - name: route-updater
          image: {{ .Values.routeUpdater.image }}
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          {{- if .Values.routeUpdater.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.routeUpdater.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.routeUpdater.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.routeUpdater.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.routeUpdater.ports }}
          ports: {{- include "common.tplvalues.render" (dict "value" .Values.routeUpdater.ports "context" $) | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.routeUpdater.resources | nindent 12 }}
          {{- with .Values.routeUpdater.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.routeUpdater.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.routeUpdater.config.enabled }}
          volumeMounts:
            - name: route-updater-config
              mountPath: /opt/update.sh
              subPath: update.sh
            - name: route-updater-config
              mountPath: /opt/crontab/crontab
              subPath: crontab
          {{- end }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.names.fullname" . }}
        {{- if and .Values.blackboxExporter.enabled .Values.blackboxExporter.config.enabled }}
        - name: bb-config
          configMap:
            name: {{ include "common.names.fullname" . }}-bb
        {{- end }}
        {{- if and .Values.routeUpdater.enabled .Values.routeUpdater.config.enabled }}
        - name: route-updater-config
          configMap:
            name: {{ include "common.names.fullname" . }}-route-updater
            defaultMode: 420
            items:
              - key: crontab
                mode: 493
                path: crontab
              - key: update.sh
                mode: 493
                path: update.sh
        {{- end }}
