## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy: []

image:
  registry: docker.io
  repository: openverso/ueransim
  tag: 3.2.6
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
  ## Enable debug mode
  ##
  debug: false

name: ueransim-ues

count: 1
initialMSISDN: '0000000001'
mcc: '999'
mnc: '70'
key: 465B5CE8B199B49FAA5F0A2EE238A6BC
op: E8ED289DEBA952E4283B54E88E6183CA
opType: OPC
gnb:
  hostname: ueransim-gnb
sst: 1
sd: "0x111111"
apnList:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: "0x111111"
    emergency: false

## @param command Override default container command (useful when using custom images)
##
command: []
## @param args Override default container args (useful when using custom images)
##
args: []

resources:
  limits: {}
  requests: {}
podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: false
podLabels: {}
podAnnotations: {}
affinity: {}
nodeSelector: {}
tolerations: []

blackboxExporter:
  enabled: false
  image: quay.io/prometheus/blackbox-exporter:v0.24.0

  args:
    - "--config.file=/config/blackbox.yaml"

  config:
    enabled: true
    data:
      modules:
          http_2xx:
            prober: http
            timeout: 5s
            http:
              valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
              follow_redirects: true
              preferred_ip_protocol: "ip4"
          tcp:
            prober: tcp
            timeout: 5s
            tcp:
              preferred_ip_protocol: "ip4"
          icmp:
            prober: icmp
            timeout: 5s
            icmp:
              preferred_ip_protocol: "ip4"

  metrics:
    enabled: true
    serviceMonitor:
      labels: {}
      honorLabels: false
      endpoints:
        scheme: http
        port: metrics
        path: "/probe"

      targets: []
        # - name: https_ya_ru
        #   url: https://ya.ru
        #   module: http_2xx
        #   interval: 30s

  service:
    enabled: true
    type: ClusterIP
    port: 9115

  ports:
    - name: metrics
      containerPort: 9115
      protocol: TCP

  resources:
    limits:
      memory: 300Mi
    requests:
      memory: 50Mi

  livenessProbe:
    httpGet:
      path: /-/healthy
      port: metrics
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /-/healthy
      port: metrics
